services:
  - type: web
    name: brainpulse-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd idp && npm install && npm run build && cd ../backend && pip install -r requirements.txt && mkdir -p static && cp -r ../idp/dist/* static/
    startCommand: cd backend && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
